### PR TITLE
fix(cli): dirname

### LINKED ISSUE #82: [bug]: CLI won't work please check description
### Describe the bug

I've tried adding `npx shadcn-solid add button` an error.

### Affected component/components

probably all

### How to reproduce

Trying to add shadcn-solid to an existing solid-start project, just using your regular `npx shadcn-solid add button` won't do.

### Codesandbox/StackBlitz link

-

### Logs

```Work/Github/starter$ npx shadcn-solid add button

node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at validateString (node:internal/validators:162:11)
    at resolve (node:path:1101:7)
    at k (file:///home/artae/.npm/_npx/8a8daac7497ab0a9/node_modules/shadcn-solid/dist/index.js:3:209)
    at Mo (file:///home/artae/.npm/_npx/8a8daac7497ab0a9/node_modules/shadcn-solid/dist/index.js:267:4225)
    at file:///home/artae/.npm/_npx/8a8daac7497ab0a9/node_modules/shadcn-solid/dist/index.js:267:4379
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  code: 'ERR_INVALID_ARG_TYPE'
```

### System Info

```bash
VanillaOS Linux

NodeJS v20.10 running in Arch container
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

### PR DESCRIPTION
**Pull request by hngngn**
fix #82

### CODE REVIEW

**Comment by hngngn** [comment]
@thednp can you test this?

**Comment by thednp** [comment]
I tested `npx shadcn-solid@0.0.0-beta.7c87b40 init` same error.

**Comment by thednp** [comment]
Are you sure import.meta.dirname is defined?

**Comment by hngngn** [comment]
well yes, i can log the dir and get the version number, but if you think this cause the problem, let me update it

**Comment by thednp** [comment]
You need to use `process.cwd()` instead. But that triggers another error:

`TypeError: (intermediate value).name(...).description(...).version is not a function
    at Mo (file:///............../node_modules/shadcn-solid/dist/index.js:267:4278)`

**Comment by hngngn** [comment]
> You need to use `process.cwd()` instead. But that triggers another error:
> 
> `TypeError: (intermediate value).name(...).description(...).version is not a function at Mo (file:///............../node_modules/shadcn-solid/dist/index.js:267:4278)`

no, is will read the project package.json

**Comment by hngngn** [comment]
@thednp check the new one

**Comment by thednp** [comment]
This npx shadcn-solid@0.0.0-beta.b925fee ?

**Comment by hngngn** [comment]
yeah

**Comment by thednp** [comment]
Seems to be working. Will let you know if any issue asap ok?

**Comment by thednp** [comment]
I think the problem is fixed, safe to say it's ready for 0.7.3 I guess.

**Comment by thednp** [comment]
@hngngn is this live now? Can I test 0.7.3?

**Comment by thednp** [comment]
Please disregard the above, I tested with latest, all working flawless. Great work ;)

**Pull request merged**
