### PR TITLE
Update cli to latest version from shadcnui (needed for tailwind prefixes to work)

### PR DESCRIPTION
**Pull request by kmiterror**
My main goal was to add support for tailwind prefixes described here
[https://tailwindcss.com/docs/configuration#prefix](https://tailwindcss.com/docs/configuration#prefix)

This was added in shadcn-ui here:
https://github.com/shadcn-ui/ui/pull/770

I basically copied the whole cli folder from shadcnui repo, and adjusted the base url so it's still the same.
I'm not sure if there is anything else  that should be adjusted.
On surface it looks good.
With this change, tailwind prefix works as intended.

PS How to actualy produce a working package with proper node_modules (at least for debugging purposes)?
`pnpm build` produces just the index.js file, but the node_modules is also needed with all the deps to make it run properly.
I'm not to familiar with how pnpm does it (I see a lot of symlinks), so I had to resort to `npm install` to get flat node_modules structure with all needed deps.

### CODE REVIEW

**Comment by kmiterror** [comment]
Ahh, I just realised that I tested only on Button component, but this was a simple case.
Other components doesn't work with prefix.
I'm guessing that all components in the registry would have to be udapted as well.
Do you have any way how this can be done quickly?

**Comment by hngngn** [comment]
Added

**Comment by kmiterror** [comment]
Hey 
I tried once more after updating the cli but now I get this error whenever I try to add new component.
Any clues?
```
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Response.json (file:///Users/marcin/.npm/_npx/8a8daac7497ab0a9/node_modules/node-fetch/src/body.js:149:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/marcin/.npm/_npx/8a8daac7497ab0a9/node_modules/shadcn-solid/dist/index.js:2:3921
    at async Promise.all (index 0)
    at async O (file:///Users/marcin/.npm/_npx/8a8daac7497ab0a9/node_modules/shadcn-solid/dist/index.js:2:3888)
    at async J (file:///Users/marcin/.npm/_npx/8a8daac7497ab0a9/node_modules/shadcn-solid/dist/index.js:2:3570)
    at async Command.<anonymous> (file:///Users/marcin/.npm/_npx/8a8daac7497ab0a9/node_modules/shadcn-solid/dist/index.js:3:1912)
```

**Comment by hngngn** [comment]
Make a new issue if you find any bugs. Thanks

**Comment by kmiterror** [comment]
I tried once more with 0.5.1 that you released yesterday and now it all works perfectly.
Components are added, prefix is added.
Awesome work.

Out of curiosity, what is your process with adjusting changes made in original shadcn/ui repo?
Is it all manual work or you have some sort of automation somewhere?

**Pull request closed without merging**
